softball/urls.py
from django.conf.urls import patterns, url
from django.views.generic.simple import redirect_to


urlpatterns = patterns('',
    url(r'^$', redirect_to, { 'url': 'team', }, name='softball_home'),
    url(r'^team/$', 'softball.views.team_list', name='team_list'),
    url(r'^team/create/$', 'softball.views.team_create', name='team_create'),
    url(r'^team/(?P<team_id>\d+)/$', 'softball.views.team_view',
        name='team_view'),
    url(r'^team/(?P<team_id>\d+)/edit/$', 'softball.views.team_edit',
        name='team_edit'),
    url(r'^team/(?P<team_id>\d+)/delete/$', 'softball.views.team_delete',
        name='team_delete'),
    url(r'^player/$', 'softball.views.player_list', name='player_list'),
    url(r'^player/create/$', 'softball.views.player_create',
        name='player_create'),
    url(r'^player/(?P<player_id>\d+)/$', 'softball.views.player_view',
        name='player_view'),
    url(r'^player/(?P<player_id>\d+)/edit/$', 'softball.views.player_edit',
        name='player_edit'),
    url(r'^player/(?P<player_id>\d+)/delete/$', 'softball.views.player_delete',
        name='player_delete'),
    url(r'^game/$', 'softball.views.game_list', name='game_list'),
    url(r'^game/create/$', 'softball.views.game_create', name='game_create'),
    url(r'^game/(?P<game_id>\d+)/$', 'softball.views.game_view',
        name='game_view'),
    url(r'^game/(?P<game_id>\d+)/edit/$', 'softball.views.game_edit',
        name='game_edit'),
    url(r'^game/(?P<game_id>\d+)/delete/$', 'softball.views.game_delete',
        name='game_delete'),
    url(r'^user/signup/$', 'softball.views.user_signup', name='user_signup'),
    url(r'^user/$', 'softball.views.user_edit', name='user_edit'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', direct_to_template, { 'template': 'index.html' }, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index2/', 'project.views.index2', name='index2'),
    url(r'^softball/', include('softball.urls')),
)

softball/models.py
import django.db.models

import calc


class Team(django.db.models.Model):
    created_on = django.db.models.DateTimeField(auto_now_add=True)
    updated_on = django.db.models.DateTimeField(auto_now=True)
    name = django.db.models.CharField('Team Name', max_length=150, db_index=True)

    def __unicode__(self):
        return self.name

    def record(self):
        wins = [r.game().winner==self for r in self.rosters.all()]
        return wins.count(True), wins.count(False)


class Player(django.db.models.Model):
    created_on = django.db.models.DateTimeField(auto_now_add=True)
    updated_on = django.db.models.DateTimeField(auto_now=True)
    name = django.db.models.CharField(max_length=150, unique=True)
    number = django.db.models.PositiveIntegerField()
    team = django.db.models.ForeignKey('Team', related_name='players',
                                       on_delete=django.db.models.CASCADE)

    class Meta:
        ordering = ["name", ]

    def __unicode__(self):
        return u'{0} #{1}'.format(self.name, self.number or 'N/A')

    def at_bats(self):
        """
        Returns the total number of at_bats for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('at_bats'))['s'] or 0
    at_bats.short_description = u'AB'

    def hits(self):
        """
        Returns the total singles, doubles, triples, and home_runs
        """
        return sum(filter(None,
            self.statistics.aggregate(django.db.models.Sum('singles'),
                                      django.db.models.Sum('doubles'),
                                      django.db.models.Sum('triples'),
                                      django.db.models.Sum('home_runs')
            ).values()))
    hits.short_description = u'H'

    def walks(self):
        """
        Returns the total number of walks for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('walks'))['s'] or 0
    walks.short_description = u'BB'

    def strikeouts(self):
        """
        Returns the total number of strikeouts for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('strikeouts'))['s'] or 0
    strikeouts.short_description = u'K'

    def runs(self):
        """
        Returns the total number of runs for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('runs'))['s'] or 0
    runs.short_description = u'R'

    def singles(self):
        """
        Returns the total number of singles for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('singles'))['s'] or 0
    singles.short_description = u'1B'

    def doubles(self):
        """
        Returns the total number of doubled for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('doubles'))['s'] or 0
    doubles.short_description = u'2B'

    def triples(self):
        """
        Returns the total number of triples for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('triples'))['s'] or 0
    triples.short_description = u'3B'

    def home_runs(self):
        """
        Returns the total number of home runs for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('home_runs'))['s'] or 0
    home_runs.short_description = u'HR'

    def rbis(self):
        """
        Returns the total number of rbis for this player
        """
        return self.statistics.aggregate(
            s=django.db.models.Sum('rbis'))['s'] or 0
    rbis.short_description = u'RBI'

    def batting_average(self):
        if self.hits() > self.at_bats():
            return 0
        return calc.average(self.at_bats(), self.hits())
    batting_average.short_description = u'AVG'

    def on_base_percentage(self):
        if self.hits() > self.at_bats():
            return 0
        return calc.on_base_percentage(
            self.at_bats(), self.walks(), self.hits())
    on_base_percentage.short_description = u'OB'

    def slugging_percentage(self):
        if self.hits() > self.at_bats():
            return 0
        return calc.slugging_percentage(self.at_bats(), self.singles(),
                                        self.doubles(), self.triples(),
                                        self.home_runs())
    slugging_percentage.short_description = u'SLG'


class Game(django.db.models.Model):
    created_on = django.db.models.DateTimeField(auto_now_add=True)
    updated_on = django.db.models.DateTimeField(auto_now=True)
    played_on = django.db.models.DateTimeField()
    location = django.db.models.CharField(max_length=150)
    home_roster = django.db.models.OneToOneField('Roster',
                                                 related_name='home_game')
    away_roster = django.db.models.OneToOneField('Roster',
                                                 related_name='away_game')

    def __unicode__(self):
        return u'{0} on {1}'.format(self.location, self.played_on, )

    @property
    def winner(self):
        if self.away_score > self.home_score:
            return self.away_roster.team
        else:
            return self.home_roster.team

    @property
    def final_score(self):
        """
        Returns the final score of the game, as recorded in the rosters, as a
        tuple (away_score, home_score)
        """
        return self.away_score, self.home_score

    @property
    def home_score(self):
        """
        Returns the score of the home team, as recorded in the home roster
        """
        return self.home_roster.player_statistics.aggregate(
            s=django.db.models.Sum('runs'))['s'] or 0

    @property
    def away_score(self):
        """
        Returns the score of the home team, as recorded in the home roster
        """
        return self.away_roster.player_statistics.aggregate(
            s=django.db.models.Sum('runs'))['s'] or 0


class Roster(django.db.models.Model):
    created_on = django.db.models.DateTimeField(auto_now_add=True)
    updated_on = django.db.models.DateTimeField(auto_now=True)
    team = django.db.models.ForeignKey('Team', related_name='rosters',
                                       on_delete=django.db.models.CASCADE)

    def __unicode__(self):
        return '{0} - {1}'.format(self.team.name, self.id)

    def game(self):
        try:
            return self.home_game
        except Game.DoesNotExist:
            return self.away_game


class Statistic(django.db.models.Model):
    created_on = django.db.models.DateTimeField(auto_now_add=True)
    updated_on = django.db.models.DateTimeField(auto_now=True)
    player = django.db.models.ForeignKey('Player', related_name='statistics')
    at_bats = django.db.models.PositiveIntegerField(u'AB', default=0)
    runs = django.db.models.PositiveIntegerField('R', default=0)
    singles = django.db.models.PositiveIntegerField('1B', default=0)
    doubles = django.db.models.PositiveIntegerField('2B', default=0)
    triples = django.db.models.PositiveIntegerField('3B', default=0)
    home_runs = django.db.models.PositiveIntegerField('HR', default=0)
    rbis = django.db.models.PositiveIntegerField('RBI', default=0)
    walks = django.db.models.PositiveIntegerField('BB', default=0)
    strikeouts = django.db.models.PositiveIntegerField('K', default=0)
    roster = django.db.models.ForeignKey('Roster',
                                         related_name='player_statistics',
                                         on_delete=django.db.models.CASCADE)

    class Meta:
        unique_together = ('player', 'roster', )

    def __unicode__(self):
        return u'{name} ({roster_id}): AB:{at_bats} R:{runs} 1B:{singles} ' \
               u'2B:{doubles} 3B:{triples} HR:{home_runs} RBI:{rbis} ' \
               u'BB:{walks} K:{strikeouts}'.format(
               name=self.player.name, roster_id=self.roster_id,
               at_bats=self.at_bats, runs=self.runs, singles=self.singles,
               doubles=self.doubles, triples=self.triples,
               home_runs=self.home_runs, walks=self.walks,
               strikeouts=self.strikeouts, rbis=self.rbis)

    def hits(self):
        return self.singles + self.doubles + self.triples + self.home_runs

    def batting_average(self):
        if self.hits() > self.at_bats:
            return 0
        return calc.average(self.at_bats, self.hits())
    batting_average.short_description = u'AVG'

    def on_base_percentage(self):
        if self.hits() > self.at_bats:
            return 0
        return calc.on_base_percentage(
            self.at_bats, self.walks, self.hits())
    on_base_percentage.short_description = u'OB'

    def slugging_percentage(self):
        if self.hits() > self.at_bats:
            return 0
        return calc.slugging_percentage(self.at_bats, self.singles,
                                        self.doubles, self.triples,
                                        self.home_runs)
    slugging_percentage.short_description = u'SLG'

softball/forms.py
from django.forms import ModelForm, ModelChoiceField
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


import models

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',)

class UserSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ('username','email','first_name', 'last_name',)

class TeamForm(ModelForm):
    error_css_class = 'text-error'
    required_css_class = 'text-required'

    class Meta:
        model = models.Team


class PlayerForm(ModelForm):
    error_css_class = 'text-error'
    required_css_class = 'text-required'

    class Meta:
        model = models.Player


class GameForm(ModelForm):
    away_team = ModelChoiceField(label=u'Away Team',
                                 required=True,
                                 queryset=models.Team.objects.all(),
                                 help_text=u'Changing the team will clear the '
                                             u'roster')
    home_team = ModelChoiceField(label=u'Home Team',
                                 required=True,
                                 queryset=models.Team.objects.all(),
                                 help_text=u'Changing the team will clear the '
                                           u'roster')
    error_css_class = 'text-error'
    required_css_class = 'text-required'

    class Meta:
        model = models.Game
        fields = ('played_on', 'location', )

    def clean(self):
        cleaned_data = self.cleaned_data
        if cleaned_data.get('home_team') == cleaned_data.get('away_team') and\
                cleaned_data['home_team']:
            msg = u'Home team and Away team cannot be the same.'
            self._errors['home_team'] = self.error_class([msg])
            self._errors['away_team'] = self.error_class([msg])
            # These fields are no longer valid. Remove them from the
            # cleaned data.
            del cleaned_data['home_team']
            del cleaned_data['away_team']
        return cleaned_data
     #      fields = ('played_on', 'location', )

class StatisticForm(ModelForm):
    def __init__(self, *args, **kwargs):
        # accept a Team to use for Player selection
        super(StatisticForm, self).__init__(*args, **kwargs)
        widget_overrides = (
            'at_bats', 'runs', 'singles', 'doubles', 'triples', 'home_runs',
            'rbis', 'walks', 'strikeouts',
        )
        # override the class of the widget_overrides fields
        for s in widget_overrides:
            self.fields[s].widget.attrs['class'] = 'input-mini right'


class GameStatisticForm(StatisticForm):
    def __init__(self, *args, **kwargs):
        self.team = kwargs.pop('team')
        super(GameStatisticForm, self).__init__(*args, **kwargs)
        # use the team to override the players field queryset
        self.fields['player'].queryset = self.team.players.all()


TeamPlayerFormSet = inlineformset_factory(models.Team, models.Player)

class GameStatisticFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super(GameStatisticFormSet, self).__init__(*args, **kwargs)
        if 'queryset' not in kwargs:
            kwargs['queryset'] = self.instance.player_statistics.all()

    def _construct_form(self, index, **kwargs):
        # override _construct_form to add self.team to the StatisticForm upon
        # creation
        kwargs['team'] = self.instance.team
        return super(GameStatisticFormSet, self)._construct_form(index, **kwargs)


class PlayerStatisticFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super(PlayerStatisticFormSet, self).__init__(*args, **kwargs)
        if 'queryset' not in kwargs:
            kwargs['queryset'] = self.instance.statistics.all()


GameStatisticModelFormSet = inlineformset_factory(
    parent_model=models.Roster, model=models.Statistic, form=GameStatisticForm,
    formset=GameStatisticFormSet, extra=15, max_num=20, fields=(
        'player', 'at_bats', 'runs', 'rbis', 'walks', 'strikeouts', 'singles',
        'doubles', 'triples', 'home_runs'
    ))


PlayerStatisticModelFormSet = inlineformset_factory(
    parent_model=models.Player, model=models.Statistic, form=StatisticForm,
    formset=PlayerStatisticFormSet, extra=0, fields=(
        'at_bats', 'runs', 'rbis', 'walks', 'strikeouts', 'singles', 'doubles',
        'triples', 'home_runs'
    ))

templates/softball/player/create.html
{% extends 'softball/base.html' %}

{% block title %}Add Player{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>Add Player</h1>
    </div>

<form action="" method="post" class="form-horizontal">
    <div class="row-fluid">
        <div class="span12">
            {% with player_form as form %}
                {% include "softball/include_form.html" %}
            {% endwith %}
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Add Player</button>
                <a class="btn" href="{% url player_list %}">Cancel</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/softball/player/edit.html
{% extends 'softball/base.html' %}

{% block title %}Edit Player: {{ player.name }}{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>Edit Player</h1>
    </div>

<form action="" method="post" class="form-horizontal">
    <div class="row-fluid">
        <div class="span12">
            {% with player_form as form %}
                {% include "softball/include_form.html" %}
            {% endwith %}
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Update Player</button>
                <a class="btn" href="{% url player_view player_id=player.id %}">Cancel</a>
            </div>
        </div>
    </div>
</form>

<div class="row-fluid">
  <div class="span12">
    <h2>Games</h2>
    <table class="table table-striped table-condensed table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>vs.</th>
          <th class="right">AVG</th>
          <th class="right">OBP</th>
          <th class="right">SLUG</th>
          <th class="right">AB</th>
          <th class="right">H</th>
          <th class="right">BB</th>
          <th class="right">K</th>
          <th class="right">R</th>
          <th class="right">1B</th>
          <th class="right">2B</th>
          <th class="right">3B</th>
          <th class="right">HR</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td><strong>Totals</strong></td>
          <td></td>
          <td class="right"><strong>{{ player.batting_average|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.on_base_percentage|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.slugging_percentage|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.at_bats|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.hits|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.walks|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.strikeouts|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.runs|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.singles|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.doubles|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.triples|default:"-" }}</strong></td>
          <td class="right"><strong>{{ player.home_runs|default:"-" }}</strong></td>
        </tr>
      </tfoot>
      <tbody>
        {% for statistic in player.statistics.all %}
          <tr>
            <td>{{ statistic.roster.game.played_on }}</td>
            <td>{{ statistic.roster.game.location }}</td>
            <td class="right">{{ statistic.batting_average|default:"-" }}</td>
            <td class="right">{{ statistic.on_base_percentage|default:"-" }}</td>
            <td class="right">{{ statistic.slugging_percentage|default:"-" }}</td>
            <td class="right">{{ statistic.at_bats|default:"-" }}</td>
            <td class="right">{{ statistic.hits|default:"-" }}</td>
            <td class="right">{{ statistic.walks|default:"-" }}</td>
            <td class="right">{{ statistic.strikeouts|default:"-" }}</td>
            <td class="right">{{ statistic.runs|default:"-" }}</td>
            <td class="right">{{ statistic.singles|default:"-" }}</td>
            <td class="right">{{ statistic.doubles|default:"-" }}</td>
            <td class="right">{{ statistic.triples|default:"-" }}</td>
            <td class="right">{{ statistic.home_runs|default:"-" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

templates/softball/player/list.html
{% extends 'softball/base.html' %}

{% block title %}Players{% endblock %}

{% block body %}
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-condensed table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Team</th>
                    <th class="right">Batting Average</th>
                    <th class="right">At Bats</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="5">
                        <div class="span4">
                            <div class="pagination pagination-left pagination-small">
                                <a class="btn" href="{% url player_create %}">Add Player</a>
                            </div>
                        </div>
                        <div class="span8">
                            <div class="pagination pagination-right pagination-small">
                                <ul>
                                    {% if players.paginator.num_pages > 1 %}
                                        <li><span>{{ players.paginator.count }} Players Total</span></li>
                                        {% if players.has_previous %}
                                            <li>
                                                <a href="?page={{ players.previous_page_number }}">
                                                    &laquo;
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="disabled">
                                                <span>&laquo;</span>
                                            </li>
                                        {% endif %}

                                        {% for page_num in players.paginator.page_range %}
                                            <li {% if page_num == players.number %}class="active"{% endif %}>
                                                <a href="?page={{ page_num }}">
                                                    {{ page_num }}
                                                </a>
                                            </li>
                                        {% endfor %}

                                        {% if players.has_next %}
                                            <li>
                                                <a href="?page={{ players.next_page_number }}">
                                                    &raquo;
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="disabled">
                                                <span>&raquo;</span>
                                            </li>
                                        {% endif %}
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            </tfoot>
            <tbody>
            {% for player in players %}
                <tr>
                    <td>
                        <a href="{% url player_view player_id=player.pk %}">
                            {{ player.name }}
                        </a>
                    </td>
                    <td>{{ player.number }}</td>
                    <td>
                        <a href="{% url team_view team_id=player.team.pk %}">
                            {{ player.team.name }}
                        </a>
                    </td>
                    <td class="right">
                        {{ player.batting_average|default:"-" }}
                    </td>
                    <td class="right">{{ player.at_bats|default:"-" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/softball/player/part.player_statistic.html
<table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
        <th>Date</th>
        <th>vs.</th>
        <th class="right">AVG</th>
        <th class="right">OBP</th>
        <th class="right">SLUG</th>
        <th class="right">AB</th>
        <th class="right">H</th>
        <th class="right">BB</th>
        <th class="right">K</th>
        <th class="right">R</th>
        <th class="right">1B</th>
        <th class="right">2B</th>
        <th class="right">3B</th>
        <th class="right">HR</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <td><strong>Totals</strong></td>
        <td></td>
        <td class="right">
            <strong>{{ player.batting_average|default:"-" }}</strong>
        </td>
        <td class="right">
            <strong>{{ player.on_base_percentage|default:"-" }}</strong>
        </td>
        <td class="right">
            <strong>{{ player.slugging_percentage|default:"-" }}</strong>
        </td>
        <td class="right">
            <strong>{{ player.at_bats|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.hits|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.walks|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.strikeouts|default:"-" }}</strong>
        </td>
        <td class="right">
            <strong>{{ player.runs|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.singles|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.doubles|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.triples|default:"-" }}</strong></td>
        <td class="right">
            <strong>{{ player.home_runs|default:"-" }}</strong></td>
    </tr>
    </tfoot>
    <tbody>
    {% for statistic in player.statistics.all %}
        <tr>
            <td>{{ statistic.roster.game.played_on }}</td>
            <td>{{ statistic.roster.game.location }}</td>
            <td class="right">{{ statistic.batting_average|default:"-" }}</td>
            <td class="right">{{ statistic.on_base_percentage|default:"-" }}</td>
            <td class="right">{{ statistic.slugging_percentage|default:"-" }}</td>
            <td class="right">{{ statistic.at_bats|default:"-" }}</td>
            <td class="right">{{ statistic.hits|default:"-" }}</td>
            <td class="right">{{ statistic.walks|default:"-" }}</td>
            <td class="right">{{ statistic.strikeouts|default:"-" }}</td>
            <td class="right">{{ statistic.runs|default:"-" }}</td>
            <td class="right">{{ statistic.singles|default:"-" }}</td>
            <td class="right">{{ statistic.doubles|default:"-" }}</td>
            <td class="right">{{ statistic.triples|default:"-" }}</td>
            <td class="right">{{ statistic.home_runs|default:"-" }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/softball/player/view.html
{% extends 'softball/base.html' %}

{% block title %}Player: {{ player.name }}{% endblock %}

{% block body %}
<div class="page-header">
    {% if player.owned_by == user %}
    <p class="pull-right">
      {% if perms.softball.delete_player %}
        <a class="btn btn-danger" href="{% url player_delete player_id=player.id %}">
          Delete Player</a>
      {% endif %}
	{% if perms.softball.change_player %}
	
        <a class="btn" href="{% url player_edit player_id=player.id %}">Edit Player</a>
	{% endif %}
    </p>
    {% endif %}
    <h1>
        {{ player.name }}
        <small>
            #{{ player.number }}
            <a href="{% url team_view team_id=player.team.id %}">
                <strong>{{ player.team.name }}</strong>
            </a>
        </small>
    </h1>
</div>

<div class="row-fluid">
    <div class="span12">
        <h3>Games</h3>
        {% include "softball/player/part.player_statistic.html" %}
    </div>
</div>
{% endblock %}